### ISSUE TITLE
Implementar stage gitDiff en pipeline CD

### ISSUE THREAD

**Issue by ganvoa** [udd-seccion2-grupo4/pipeline-devops#6]
Consideraciones según enunciado:

- Mostrar por pantalla las diferencias entre la rama release en curso y la rama master.

**Comment by inyerade** [comment]
dejaré creado el stage con un texto TODO ya que estoy en lo de renombrar los stages

**Comment by pcamposti** [comment]
if (currentStages.contains(gitdiff)) {
        stage(gitdiff) {
            sh "git config --add remote.origin.fetch +refs/heads/main:refs/remotes/origin/main"
            sh "git fetch --no-tags"
            sh " git diff origin/main origin/${env:BRANCH_NAME}"
        }
    }
